### ISSUE TITLE
Using pypreprocess after a long time

### ISSUE THREAD

**Issue by eickenberg** [neurospin/pypreprocess#104]
Since the API has changed somewhat since I last used this, I am taking advantage of my empty slate state to attack this software package as a newbie. In particular I would like to start using the config file approach, if possible.

Concerning this, I don't seem to be able to load https://github.com/neurospin/pypreprocess/wiki/Example-scripts 
Has this moved?

**Comment by dohmatob** [comment]
Hi @eickenberg,

Thanks for using our broken products (with absolutely no warranty, not even warranty ensuring usability of any kind, etc.). Yes we've deleted the wiki pages because we reckoned users wouldn't look at them. The info those wiki pages used to contain are now show-cased in the readme https://github.com/neurospin/pypreprocess/blob/master/README.rst in-place.

Waiting you here more.

**Comment by eickenberg** [comment]
OK I found that, thanks. I will then delete the link to the wiki page if you don't mind.

**Comment by dohmatob** [comment]
... so I'm removing the broken link https://github.com/neurospin/pypreprocess/wiki/Example-scripts

**Comment by eickenberg** [comment]
OK thanks

**Comment by dohmatob** [comment]
Done.

**Comment by eickenberg** [comment]
This is unlikely the only thing I will have to ask about. Do you want me to open a new issue for everything? I thought of collecting the things here, because they are pretty minor and not really worth a full issue in itself.

**Comment by dohmatob** [comment]
I've just made some amendments to the readme to render things more informative.

**Comment by eickenberg** [comment]
When using .ini files, is it possible to refer, in the specification of the path to the functional files, to the name of the subject? All files and folder I have contain the subject name. If I wildcard to hard, I may get too many files...

**Comment by eickenberg** [comment]
Is there an example that uses SPM standalone? The ini files I see need the specification of a matlab executable

**Comment by eickenberg** [comment]
> The ini files I see need the specification of a matlab executable

Sry not true for `nyu_rest_preproc.ini`. But I assume it still looks for matlab by default?

**Comment by dohmatob** [comment]
- You only need to specify matlab or spm path when you're running on YOD
(your-own-device). If running on drago, then pypreprocess will auto-locate
pre-compiled SPM, etc.. Similar story for CEA machines.
The logic is implemented in pypreprocess/configure_spm.py

- You can open an ticket per issue or a ticket for all your issues. Just do
as it suites you, I'm fine with either way.


On Wed, May 6, 2015 at 2:19 PM, eickenberg <notifications@github.com> wrote:

> The ini files I see need the specification of a matlab executable
>
> Sry not true for nyu_rest_preproc.ini. But I assume it still looks for
> matlab by default?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/104#issuecomment-99428187>
> .
>



-- 
DED

**Comment by eickenberg** [comment]
`SubjectData` has optional arguments (e.g. output directories) that seem to be mandatory in the sense that they are needed and not imputed by functionality using this structure. In at least one function relying on `SubjectData` these values are also not mandatory and thus cause an assertion error.

The only reason to keep the arguments non-mandatory in `SubjectData` is if it is not clear at creation, but ensured that this information is added somehow somewhere along the processing line, implying the existence of compulsory arguments or imputation in this respect in all outward facing functionality.

Maybe I am missing something crucial?

**Comment by dohmatob** [comment]
@eickenberg: Thanks for reporting this. You're absolutely right. Almost all of the arguments of SubjectData constructor should be optional. I'll fix this immediately. Could you please copy-paste the error message thrown, so I can roll a test case to bullet-proof this ?

**Comment by eickenberg** [comment]
for example not specifying `output_dir` leads to this when calling `do_subject_preproc`

```
   1210             "got %s" % type(subject_data))
   1211 
-> 1212     subject_data.sanitize(deleteorient=deleteorient, niigz2nii=True)
   1213     subject_data.failed = False
   1214 

/home/me232320/.local/lib/python2.7/site-packages/pypreprocess/subject_data.pyc in sanitize(self, deleteorient, niigz2nii)
    348 
    349         # sanitize output_dir
--> 350         self._sanitize_output_dir()
    351 
    352         # .dcm, .ima -> .nii

/home/me232320/.local/lib/python2.7/site-packages/pypreprocess/subject_data.pyc in _sanitize_output_dir(self)
    161     def _sanitize_output_dir(self):
    162         # output dir
--> 163         assert not self.output_dir is None
    164         self.output_dir = os.path.abspath(self.output_dir)
    165         if not os.path.exists(self.output_dir):

AssertionError: 

```

**Comment by dohmatob** [comment]
OK, thx. It looks like the SubjectData object is a nest for potential bugs. Looking into this.

**Comment by dohmatob** [comment]
See PR #105. Once travis is green, I merge.

**Comment by dohmatob** [comment]
Any update ?

**Comment by dohmatob** [comment]
OK, I conclude everything is OK. Closing issue.

**Comment by eickenberg** [comment]
Yeah, sorry for not getting back. Conclusion: I wasn't able to use the
config files in a straightforward way to preprocess my data (probably due
to a lack of understanding) and so resorted to using pypreprocess at the
python level, which worked.
