### ISSUE TITLE
_utils.check_niimgs does not exist in nilearn 0.1.3

### ISSUE THREAD

**Issue by lesteve** [neurospin/pypreprocess#106]
Not sure what you want to do and whether you want to support nilearn > 0.1.3 and nilearn 0.1.2. Also there is the more general question of whether code in _utils should be used outside nilearn ... cc @GaelVaroquaux @bthirion @AlexandreAbraham 

The fix for nilearn 0.1.3 is to use _utils.check_niimg_4d or _utils.check_niimg should be used. The latter is to be used only if the input image is 3d or 4d I think. @AlexandreAbraham may remember more about these subtleties.

**Comment by lesteve** [comment]
For reference I bumped on this when rebasing #100. The error is [here](https://travis-ci.org/neurospin/pypreprocess/builds/62425972).

**Comment by AlexandreAbraham** [comment]
> whether you want to support nilearn > 0.1.3 and nilearn 0.1.2

Since we are un dev mode, I would be in favor of supporting >= 0.1.3

>  whether code in _utils should be used outside nilearn

Prefixed module can be used outside but with no guarantee.

> The fix for nilearn 0.1.3 is to use _utils.check_niimg_4d or _utils.check_niimg

For most cases `check_niimg_4d` should do.

**Comment by GaelVaroquaux** [comment]
_utils is private, which means that it shouldn't be used outside of nilearn.

**Comment by dohmatob** [comment]
I'm about to close this isssue. @lesteve  can you confirm this is now fixed in master (pypreprocess) ?
