### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by arokem** [neurospin/pypreprocess#107]
Is this code released under any particular license? I might have missed it, but couldn't find any license information. Thanks!

**Comment by bthirion** [comment]
Hi Ariel, 

We do not particularly try to advertize it, because it will bring us more trouble than reward. Take its as BSD-licensed (we should add it explicitly). 

Bertrand 

----- Mail original -----

**Comment by dohmatob** [comment]
I've added BSD 3clause license in readme. Closing the issue.
