### ISSUE TITLE
Some issues when preprocessing with DARTEL

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#118]
I ran a preprocessing pipeline with `DARTEL`.
While the processing went fine, I've noted some issues mainly on the report :
* `plot_cv_tv` is not performed even with the flag `plot_cv_tv = True`
* The main `report_preproc.html` is empty and does not contain the  `mean functional image_on_template_outline_axial` thumbnail of the subjects.
* The outline of the segmentation on the images is wrong. 

e. g. :
This is what resulted with the report :
![subject_tmps_contours_on_subject_anatomical image](https://cloud.githubusercontent.com/assets/8612476/7912503/56015d12-0868-11e5-89ee-aa1c47f4f236.png)

This is what actually is with the correct warped anatomical image (same thing for the functional) :
![outline](https://cloud.githubusercontent.com/assets/8612476/7912518/76a2e84c-0868-11e5-978a-65617dccde3f.png)

* Also, the resampling of the functional and anatomical gives `double` data which is quite huge.

**Comment by dohmatob** [comment]
Also:
* The one-thumb-per-subject report page show coreg output instead of normalization output

**Comment by mrahim** [comment]
The resampling issue is related to a wrong `dtype` when handling 4d images in `resample_img` of `nilearn.image`. This was reported to @lesteve

**Comment by dohmatob** [comment]
Cool. Thanks for the autopsy. We'll need a regression test for this, it's
been fixed upstream.

On Tue, Jun 2, 2015 at 2:44 PM, mrahim <notifications@github.com> wrote:

> The resampling issue is related to a wrong dtype when handling 4d images
> in resample_img of nilearn.image. This was reported to @lesteve
> <https://github.com/lesteve>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/118#issuecomment-107941671>
> .
>



-- 
DED

**Comment by lesteve** [comment]
see https://github.com/nilearn/nilearn/pull/598.

**Comment by dohmatob** [comment]
See PR #119 fixing this issue (at least the Dartel parts of the problem).
