### ISSUE TITLE
Make code Python 3 compatible

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#128]
Pypreprocess is not Python 3 compatible. It should be fairly easy to solve this automatically by fixing a couple of "print" statements,  xrange ==> range, etc.

**Comment by AlexandreAbraham** [comment]
If you don't want to depend on six or future, you can cherry pick some workarounds in `nilearn._utils.compat`.

**Comment by KamalakerDadi** [comment]
With @arthurmensch, it seems like we will not be able to do Python 3 compatible since we have huge dependency in nipype and nipype is not well organized to Python 3. So, we can close this issue if you want.

**Comment by dohmatob** [comment]
OK, Closing.

**Comment by AlexandreAbraham** [comment]
> we depend on nipype, and it doesn't support it

Sorry to shatter your dreams, Nipype does support Python 3. Back to work guys :smiling_imp:
