### ISSUE TITLE
Remove bunched joblib from pypreprocess/external

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#129]
We should use joblib from nilearn or sklearn instead.

**Comment by bthirion** [comment]
Maybe nilearn is the most sensible option.

**Comment by GaelVaroquaux** [comment]
> Maybe nilearn is the most sensible option.

nilearn doesn't embed joblib. It gets it through scikit-learn.

**Comment by dohmatob** [comment]
Fixed.
