### ISSUE TITLE
missing __version__ 

### ISSUE THREAD

**Issue by chrplr** [neurospin/pypreprocess#133]
Trying to determine which version of pypreprocess I am using, I find that 

pypreprocess.__version__ 

does not exist

**Comment by KamalakerDadi** [comment]
@dohmatob You already made a PR I see? What is still lacking here ?

**Comment by dohmatob** [comment]
Maybe a small unit test ?

**Comment by KamalakerDadi** [comment]
>Maybe a small unit test ?

unit test on pypreprocess dependencies ?

**Comment by dohmatob** [comment]
Sorry for the imprecision. I meant a small unit test to check that the version issue raised here is solved.

**Comment by mrahim** [comment]
I think we can close this.
