### ISSUE TITLE
Make pyreprocess hyperlink in report page open in a new tab

### ISSUE THREAD

**Issue by estheryclin** [neurospin/pypreprocess#167]
It'd be nice to make the pyreprocess hyperlink (when the logo is clicked) in report page open in a new tab

**Comment by AlexandreAbraham** [comment]
-1 on this. FIrst, this is impossible as there is no technical way to force opening a page in a tab. We can only force a new window. Second, this is a user decision whether to open it in a tab or in the same page. Finally, this behavior is highly incompatible with modern systems such as smartphones. The case of forcing the page to open in a new window is not very well handled.

**Comment by dohmatob** [comment]
@estheryclin: Thanks for reporting this. As @AlexandreAbraham points out, apparently, it looks like it's a user's decision to take. So, lemme close this for now.  Reopen it if you have an objection :)
