### ISSUE TITLE
Replace nipy dependency with nistats

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#172]
Ship the (light-weight, pure Python) nistats code into pypreprocess.
Note tyhat this adds a dependency on pandas

**Comment by mrahim** [comment]
Basically, we should replace `design_matrix`, `Paradigm`, `glm`, and some functions that exist in nilearn (e.g. : `intersect_mask`).

**Comment by dohmatob** [comment]
I don't mind depending on pandas since pypreprocess is all about big data :)

**Comment by dohmatob** [comment]
nipy ==> nistats successfully. Closing.
