### ISSUE TITLE
generate_coregistration_thumbnails requires holding all fmri data in memory 

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#173]
Which is too demanding: 6 runs of shape 128 * 128 * 84 * 315 break the 16GB memory of my desktop computer. Since we only need the average EPI volume , we can certainly avoid this.

**Comment by AlexandreAbraham** [comment]
>  Since we only need the average EPI volume

According to the code, the first volume is used, not the mean. Also, from what I see in the code, each file is loaded for the plotting and then discarded so it should not stay in memory.

I can try to investigate this one. Does somebody have piece of code to reproduce?

**Comment by bthirion** [comment]
Solved by #249. Closing
