### ISSUE TITLE
Where preprocessing outputs should be saved ?

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#176]
I'm wondering what is the best way to set the output paths when running the examples.
Actually three options exist in the examples, I think we should unify according to one strategy:
- `/tmp` : Not very intuitive.
- script folder : it can be limited by user quota for example.
- data folder : we might have issues if data folders are read-only.

Comments are welcome. @lesteve @GaelVaroquaux @bthirion

**Comment by GaelVaroquaux** [comment]
>   • script folder : it can be limited by user quota for example.

This one. At least users are more likely to see this.

**Comment by bthirion** [comment]
Looks like we agree. Closing.
