### ISSUE TITLE
Output image names in reports  includes spaces

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#179]
Which makes it difficult to (re-)use them

**Comment by mrahim** [comment]
The filenames are :
* `anatomical image_on_mean functional image_outline.png`
* `mean functional image_on_anatomical image_outline_axial.png`
* `mean functional image_on_anatomical image_outline.png`
* `subject_tpms_contours_on_subject_anatomical image_axial.png`
* `subject_tpms_contours_on_subject_anatomical image.png`
* `subject_tpms_contours_on_subject_mean functional image_axial.png`
* `subject_tpms_contours_on_subject_mean functional image.png`
