### ISSUE TITLE
in ini files, cannot use mutliple wildcards for a list of files

### ISSUE THREAD

**Issue by chrplr** [neurospin/pypreprocess#181]
something like 

      subjects_dir = sub01* sub02* 

will not work

**Comment by dohmatob** [comment]
This is not intended to work. Why not just do sub* ?

On Mon, Jan 25, 2016 at 5:55 PM, Christophe Pallier <
notifications@github.com> wrote:

> something like
>
>   subjects_dir = sub01* sub02*
>
> will not work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/181>.
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by AlexandreAbraham** [comment]
@chrplr, the syntax used here is globbing. You can learn more here: https://en.wikipedia.org/wiki/Glob_%28programming%29

What you want is `sub0[12]*`.

**Comment by chrplr** [comment]
Why not consider that the argument of 'subjects_dirs' is a *list of
patterns* for globbing?
The behavior would be the same as on any standard shell command line where
each pattern is expanded.
Would this cause any trouble?  I do not think so (?).

Now, here is what lead me to this:

@Elvis

       subjects_dirs = sub*


crashed with an 'Out of Memory', so I had to split the ini file into
several ini files corresponding to several subgroups of subjects


@Alexandre

The real life problem was more complex than the example I provided and
simple globbing would not have worked:

The directory names had a format subXX_YYYYYYYYY where YYYYYYYY was
essentially arbireatyr (nip code)
and the XX was a arbirary subset of numbers between 01 and 29.  (and I was
too lazy to copy the output of 'ls'  inside ini files).

Now, the ugly solution that worked was to  generate a bunch of independent
ini files.
It is a pity not to be allowed to use a single ini file with the pattern
'sub*'  because of the out of memory issue.

The pipeline we use to use was sequential and there was no risk of running
out of memory after the first S.
I learned the hard way that I must estimate to memory load to avoid
overloading pypreprocess at the risk of running out of memory.
If there was some black magic allowing pypreprocess to automatically avoid
out of memory, that would be great.
Best,

Chris





--
Christophe Pallier

Contact info: http://www.pallier.org/w/pmwiki.php/Main/Contact

On Mon, Jan 25, 2016 at 6:16 PM, Alexandre Abraham <notifications@github.com

**Comment by dohmatob** [comment]
OK, the use case of @chrplr is perfectly legit, and should it be straight-forward to implement a fix. I'll allocate time to do this asap. Anybody else should feel free to submit a PR. You simply need to change this line https://github.com/neurospin/pypreprocess/blob/master/pypreprocess/conf_parser.py#L294, and add an appropriate test in `pypreprocess/tests/test_conf_parser.py`.

**Comment by dohmatob** [comment]
@chrplr: To check that the above PR solves your problem, you'd do something like:

```
from pypreprocess.conf_parse import import_data
subjects, _ = import_data("my_ini_file_with_list_of_wildcards.ini")
```
and then check that `subjects` has the expected length and contents.

**Comment by dohmatob** [comment]
No feedback, closing.
