### ISSUE TITLE
Clean temporary output items (tmp, joblib ...)

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#186]
This seems to me as a recurrent task after finishing a preprocessing pipeline.
Usually the dataset size is divided by 4  (depends on the pipeline).
We could imagine a similar function to what we have in [`continuous_integration/clean_output.sh`](https://github.com/neurospin/pypreprocess/blob/master/continuous_integration/clean_output.sh).

**Comment by bthirion** [comment]
Related to #203. Closing.
