### ISSUE TITLE
spm_mcr variable in .ini not taken into account

### ISSUE THREAD

**Issue by chrplr** [neurospin/pypreprocess#189]
Although I put 

spm_mcr = /i2bm/local/bin/spm12

in an ini file, the spm8 mcr was used

**Comment by isadenghien** [comment]
Yes I had the same beharviour. If SPM_MCR for SPM12 is not a environment variable on your system, and if you add this value into the config.ini file.
So pypreprocess doesn't read it and uses the default value for SPM8.
But if SPM_MCR  is SPM_MCR="/usr/local/bin/spm12" for instance in your bashrc, it works.

**Comment by dohmatob** [comment]
@isadenghien: if you re-pull, re-install, and re-run this should now be fixed. Please can you confirm ?

**Comment by dohmatob** [comment]
OK, I got confirmation. Closing.
