### ISSUE TITLE
seems like slice timing was started even if not requested (or maybe just a normal message?)

### ISSUE THREAD

**Issue by chrplr** [neurospin/pypreprocess#190]
Although the .ini (attached) contains the following option to disable slice timing:

-----
     # Don't you want us to do Slice-Timing Correction (STC) ?
     disable_slice_timing = True
----

pypreprocess printed the following on stdout:

[Memory] Calling pypreprocess.time_diff.multi_session_time_slice_diffs...
multi_session_time_slice_diffs([ '/media/mfabre/fmri_language/Syntmov/processed_fmri_data3/subj24_dg140032/fMRI/acquisition1/rasent1_dg140032_20140623_03.nii', ...
__________________________________multi_session_time_slice_diffs - 58.1s, 1.0min

[the-mother_of_all_preprocessing.ini.txt](https://github.com/neurospin/pypreprocess/files/121238/the-mother_of_all_preprocessing.ini.txt)

**Comment by bthirion** [comment]
This is not slice timeing correction, but tsdiffana, attol used to check the presence of artefacts in the data.

**Comment by chrplr** [comment]
Oops. Thanks. Sorry for the false alarm.
