### ISSUE TITLE
the images output by preprocessing pipelines should be gzipped

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#191]
The current pipeline is very greedy in memory.

**Comment by mrahim** [comment]
I think SPM (still) doesn't read `nii.gz` files.

**Comment by bthirion** [comment]
But then this could be an option. I only use SPM for pre-processing (and so do many people who work on RS data). When writing to disk the cached outputs, there could be an option to gzip the output.

**Comment by mrahim** [comment]
I'm on it.
