### ISSUE TITLE
pypreprocess logo was plagiarized from the net. This is dangerous, we should make ours.

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#198]
pypreprocess logo was plagiarized from the net. This is dangerous, we should make ours!

**Comment by AlexandreAbraham** [comment]
Ça va dans le bon sens!

You should ask on the Neurospin list, we have some designers out of the common in it.

**Comment by bthirion** [comment]
Just curious: does any remember whether the Nilearn logo is protected ?

**Comment by dohmatob** [comment]
From first sight, it logs very close to nipy / nipype logo, with some
colors flipped.

On Fri, Feb 26, 2016 at 11:39 AM, bthirion <notifications@github.com> wrote:

> Just curious: does any remember whether the Nilearn logo is protected ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/198#issuecomment-189212628>
> .
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by AlexandreAbraham** [comment]
> Just curious: does any remember whether the Nilearn logo is protected ?

It is a mix of nipy logo with scikit learn. Given that it is not an existing logo, I guess that we are not in trouble.

**Comment by AlexandreAbraham** [comment]
Mehdi exhorted me to share this experiment

![snakepixel](https://cloud.githubusercontent.com/assets/1647301/15609167/b92dee00-241e-11e6-9bc3-360f8be68481.png)

**Comment by alpinho** [comment]
Whooh, this is a good idea. I like it! We can explore this concept.

**Comment by alpinho** [comment]
Like in nilearn logo, we can have the word pypreprocess divided in two lines: py (on the top) and preprocess in the (bottom). The prefix pre- should also be emphasize. Not sure whether I like the logo in greyscale.

**Comment by AlexandreAbraham** [comment]
> Like in nilearn logo

The nilearn logo is inspired from the sklearn one. We should maybe not copy the style of the logo for pypreprocess given that it is not sklearn based.

> Not sure whether I like the logo in greyscale.

You can propose colors and I will apply them :)

**Comment by alpinho** [comment]
We should also recall SPM here, since it is highly used. What about red, blue and white, which is also the french flag colours.

**Comment by dohmatob** [comment]
On Fri, May 27, 2016 at 3:56 PM, Ana Luísa Pinho <notifications@github.com>
wrote:

> We should also recall SPM here, since it is highly used. What about red,
> blue and white, which is also the french flag colours.
>
No, the logo should not have a rainbow color gradient indicaticating every
possible dependency (like in the IBC logo...). We just want a basic
beautiful logo that reprensents pypreprocess alone.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/198#issuecomment-222152938>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAms1Jb0lSEudllOt9H_JjsHxZQMSObXks5qFvglgaJpZM4HjnIX>
> .
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by dohmatob** [comment]
On Fri, May 27, 2016 at 4:07 PM, Elvis Dohmatob <gmdopp@gmail.com> wrote:

>
>
> On Fri, May 27, 2016 at 3:56 PM, Ana Luísa Pinho <notifications@github.com
> > wrote:
>
>> We should also recall SPM here, since it is highly used. What about red,
>> blue and white, which is also the french flag colours.
>>
> No, the logo should not have
>
should'nt have*

> a rainbow color gradient indicaticating every possible dependency (like in
> the IBC logo...). We just want a basic beautiful logo that reprensents
> pypreprocess alone.
>
—
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/neurospin/pypreprocess/issues/198#issuecomment-222152938>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAms1Jb0lSEudllOt9H_JjsHxZQMSObXks5qFvglgaJpZM4HjnIX>
>> .
>>
>
>
>
> --
> Elvis Dohmatob,
> *sent from my  potato...*
> http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
> https://github.com/dohmatob
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by dohmatob** [comment]
Cool. This looks great.

On Fri, May 27, 2016 at 3:21 PM, Alexandre Abraham <notifications@github.com
> wrote:

> Mehdi exhorted me to share this experiment
>
> [image: snakepixel]
> <https://cloud.githubusercontent.com/assets/1647301/15609167/b92dee00-241e-11e6-9bc3-360f8be68481.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/198#issuecomment-222144578>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAms1Ewl-RRCoWPlmoHCuHTXKhYZ9IGNks5qFu_wgaJpZM4HjnIX>
> .
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by dohmatob** [comment]
Can someone suggest a PR with the above logo ? It'd be gr8. Thanks in advance.

**Comment by mrahim** [comment]
Closed by #248
