### ISSUE TITLE
subject_data contains links to the cache

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#205]
while it should contain only paths of database locations.

**Comment by mrahim** [comment]
Could you be more specific ?

**Comment by arthurmensch** [comment]
Should we remove cache from output ?

**Comment by dohmatob** [comment]
I am unable to reproduce this issue. Ping @bthirion.

**Comment by bthirion** [comment]
I get the issue when running the  `nipype_preproc_spm_auditory.py` example.
`subject_data['gm'] ` points to the cache.
This may be related to the use of NewSegment ?

**Comment by KamalakerDadi** [comment]
>This may be related to the use of NewSegment ?

yes, problem with NewSegment

**Comment by mrahim** [comment]
I'm on it.

**Comment by mrahim** [comment]
A final `hard_link` is missing in `do_subjects_preproc`.
Tricky to find but easy to fix.

**Comment by KamalakerDadi** [comment]
>Tricky to find but easy to fix. 

Great @mrahim
