### ISSUE TITLE
Wrong plots in auditory example report

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#206]
Some output plots are weird (e.g.: coreg, tsdiffana).

https://circle-artifacts.com/gh/mrahim/pypreprocess/208/artifacts/0/home/ubuntu/nilearn_data/spm_auditory/pypreprocess_output/report_preproc.html

**Comment by dohmatob** [comment]
Especially [these](https://circle-artifacts.com/gh/mrahim/pypreprocess/208/artifacts/0/home/ubuntu/nilearn_data/spm_auditory/pypreprocess_output/sub001/reports/report_preproc.html). I just had a quick look, at it seems a step (realign ?) of the preprocessing producess nans in the data.

**Comment by dohmatob** [comment]
OK, the problem appears to come from the Realign node.

**Comment by dohmatob** [comment]
**Update:** It seems the issue is that SPM produces NaNs, in any case. tsdiffana should do nanmean, nanstd, etc., instead of mean, std, etc. to be robust to this.

**Comment by bthirion** [comment]
Regarding the coreg plots, the issue is actually in Nilearn (see issue #1105) and should be handled there. Closing.
