### ISSUE TITLE
Makefile should be edited to remove doc tests which doesn't exists

### ISSUE THREAD

**Issue by KamalakerDadi** [neurospin/pypreprocess#219]
nosetests -s --with-doctest --doctest-tests --doctest-extension=rst \
--doctest-extension=inc --doctest-fixtures=_fixture doc/ \

```Failure: OSError (No such file /home/kamalakar/Kamalakar/work/pypreprocess/doc) ... ERROR```

**Comment by KamalakerDadi** [comment]
I don't think it is so important since we can run test using ```make test-code``` where this problem doesn't persists. If agrees we can close or ?

**Comment by dohmatob** [comment]
Fixed.
