### ISSUE TITLE
cache is not relocatable

### ISSUE THREAD

**Issue by chrplr** [neurospin/pypreprocess#234]
pypreprocess.py crashed after filling up the filesytem where I had put the cache with the 'scratch' option.

Rather than starting again from scratch (!), I decided to move the cache to a new location and modify the scratch variable accordingly.

Yet, relaunching pypreprocessed crashed because it could not find tone of the original functional file (it was searching for it in the cache rather than in the acquisition directory).

I could 'solve' the problem using a symlink, but it would be nice if the cache was relocatable.

**Comment by dohmatob** [comment]
@chrplr I don't see how you can relocate cache and resume a computation (i.e without recomputing stuff). The jobfiles embedded in the cache directory contain MD5-tagged absolute paths to intermediate input / out files. You'd need to appropriately change all these hashes, which is simply not possible.

**Comment by chrplr** [comment]
Ok. Got it. 

Yet, remark that in my case, the source files (dataset_dir) has not changed location, I had just moved the cache. And the outcome was a crash of pypreprocess, rather than just a recomputation from the beginning.
