### ISSUE TITLE
. continuous_integration/install.sh instantly crash

### ISSUE THREAD

**Issue by CherkaouiHamza** [neurospin/pypreprocess#301]
running `. continuous_integration/install.sh` makes the terminal itself crash and exit...

Should we definitely remove spm8 back-end and all the unstable-dead codes that come with it?

**Comment by bthirion** [comment]
Yes, we should not consider spm8 any more.

**Comment by CherkaouiHamza** [comment]
After, re-taking a look at install.sh, it's not a spm8 matter. Yet, it stills crash and yep we should not consider spm8 any more. And thus the installation also.
