### ISSUE TITLE
Deprecated matplotlib attributes used that make test fail unconditionnally

### ISSUE THREAD

**Issue by thomasbazeille** [neurospin/pypreprocess#317]
ax.hold() in two files :
pypreprocess/reporting/preproc_reporter.py:872
pypreprocess/time_diff.py:233

As proposed by @KamalakerDadi, in the PR that takes care of that, we should use something like
``
from distutils.version import LooseVersion
if LooseVersion(matplotlib.__version__) > LooseVersion("2.0"):
     ax.hold()
``

This is preventing pending PRs to be merged without any relation to their content and should be fixed urgently

**Comment by KamalakerDadi** [comment]
We support from matplotlib 0.99.1. So, my idea was to add check on matplotlib version for < 2.0. This holds in the code base but not in examples. As examples should be run on recent version.
 or 
We could bump the matplotlib version ?

**Comment by bthirion** [comment]
Please bump the matplotlib version: align it to that of Nilearn.

**Comment by thomasbazeille** [comment]
Solved by #319
