### ISSUE TITLE
slice_timing_demos.py seems broken and unmaintained

### ISSUE THREAD

**Issue by alpinho** [neurospin/pypreprocess#74]
/usr/local/lib/python2.7/dist-packages/pypreprocess/reporting/preproc_reporter.pyc in _get_time_series_from_voxel(x, voxel)
    945         if isinstance(x, np.ndarray):
    946             if x.ndim == 3:
--> 947                 return x[voxel[0], voxel[1], voxel[2]]
    948             else:
    949                 assert x.ndim == 4 == len(voxel) + 1

IndexError: index (20) out of range (0<=index<10) in dimension 1
> /usr/local/lib/python2.7/dist-packages/pypreprocess/reporting/preproc_reporter.py(947)_get_time_series_from_voxel()
    946             if x.ndim == 3:
--> 947                 return x[voxel[0], voxel[1], voxel[2]]

**Comment by dohmatob** [comment]
Fixed.
