### ISSUE TITLE
Dependence on  nipy.labs.statistical_mapping

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#75]
in pypreprocess/reporting/glm_reporter.

This dependence is problematic because it goes to nipy compiled code. A pure-python equivalent is however easy to set up

**Comment by dohmatob** [comment]
Agreed.

On Wed, Mar 25, 2015 at 12:58 PM, bthirion <notifications@github.com> wrote:

> in pypreprocess/reporting/glm_reporter.
>
> This dependence is problematic because it goes to nipy compiled code. A
> pure-python equivalent is however easy to set up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/75>.
>



-- 
DED

**Comment by dohmatob** [comment]
Fixed.
