### ISSUE TITLE
IndexError: index 20 is out of bounds for axis 1 with size 10

### ISSUE THREAD

**Issue by alpinho** [neurospin/pypreprocess#81]
/home/analu/git_repo/pypreprocess/examples/slice_timing_demos.py in <module>()
    404 
    405 if __name__ == '__main__':
--> 406     # demo on simulated data
    407     demo_random_brain()
    408     demo_sinusoidal_mixture()

/home/analu/git_repo/pypreprocess/examples/slice_timing_demos.py in demo_random_brain(n_rows, n_columns, n_slices, n_scans)
     37 
     38     # QA clinic
---> 39     generate_stc_thumbnails(brain_data, stc.get_last_output_data(), '/tmp/')
     40     plt.show()
     41 

/home/analu/git_repo/pypreprocess/pypreprocess/reporting/preproc_reporter.pyc in generate_stc_thumbnails(original_bold, st_corrected_bold, output_dir, voxel, sessions, results_gallery, execution_log_html_filename)
    934                                             st_corrected_bold):
    935 
--> 936         stc_ts = _get_time_series_from_voxel(stc_bold, voxel)
    937         o_ts = _get_time_series_from_voxel(o_bold, voxel)
    938         output_filename = os.path.join(output_dir,

/home/analu/git_repo/pypreprocess/pypreprocess/reporting/preproc_reporter.pyc in _get_time_series_from_voxel(x, voxel)
    916         if isinstance(x, np.ndarray):
    917             if x.ndim == 3:
--> 918                 return x[voxel[0], voxel[1], voxel[2]]
    919             else:
    920                 assert x.ndim == 4 == len(voxel) + 1

IndexError: index 20 is out of bounds for axis 1 with size 10
> /home/analu/git_repo/pypreprocess/pypreprocess/reporting/preproc_reporter.py(918)_get_time_series_from_voxel()
    917             if x.ndim == 3:
--> 918                 return x[voxel[0], voxel[1], voxel[2]]
    919             else:

**Comment by dohmatob** [comment]
Fixed.
