### ISSUE TITLE
Scripts sharing the same input data set

### ISSUE THREAD

**Issue by alpinho** [neurospin/pypreprocess#82]
The following scripts

* ~/examples/coreg_demos.py, 
* ~/examples/nipype_preproc_spm_auditory.py, 
* ~/examples/purepython_preproc_demo.py,  
* ~/examples/realign_demos.py, 
* ~/pypreprocess/datasets.py,
* ~/pypreprocess/tests/test_realign.py,
* ~/pypreprocess/tests/test_slice_timing.py

take the same input data set 

* 'fetch_spm_auditory_data',  from different paths. 

The input data shall be stored on a unique pathway for all scripts and the script shall recognize whether the input data has been already stored in the respective pathway.

**Comment by alpinho** [comment]
The scripts 'examples/nipy_glm_fsl_feeds_fmri.py' and 'examples/realign_demos.py' also share the same input data set 'fetch_fsl_feeds_data'. The input data set doesn't share the same pathway on both scripts, as well.

**Comment by alpinho** [comment]
The scripts 

~/examples/coreg_demos.py and 
~/examples/nipype_preproc_spm_nyu.py 

share the same input data set 

'fetch_nyu_rest'.

**Comment by alpinho** [comment]
The scripts

~/examples/nipype_preproc_spm_multimodal_faces.py
~/examples/realign_demos.py
~/examples/slice_timing_demos.py
~/pypreprocess/datasets.py
~/pypreprocess/glm_utils.py
~/sprint.py

share the same input data set

fetch_spm_multimodal_fmri_data

**Comment by dohmatob** [comment]
Fixed.
