### ISSUE TITLE
TypeError: sanitize() got an unexpected keyword argument 'do_deleteorient'

### ISSUE THREAD

**Issue by alpinho** [neurospin/pypreprocess#87]
TypeError                                 Traceback (most recent call last)
/home/analu/git_repo/pypreprocess/examples/coreg_demos.py in <module>()
     86 
     87 # NYU rest demo
---> 88 for subject_id, func, anat in _nyu_rest_factory():
     89     print "%s +++NYU rest %s+++\r\n" % ("\t" * 5, subject_id)
     90     _run_demo(func, anat)

/home/analu/git_repo/pypreprocess/examples/coreg_demos.py in _nyu_rest_factory(session)
     77         subject_data.output_dir = "/tmp/%s" % subject_id
     78 
---> 79         subject_data.sanitize(do_deleteorient=True, do_niigz2nii=False)
     80 
     81         yield (subject_data.subject_id, subject_data.func[0],

TypeError: sanitize() got an unexpected keyword argument 'do_deleteorient'

**Comment by dohmatob** [comment]
Should be fixed now.
