### ISSUE TITLE
TypeError: _do_subject_normalize() got an unexpected keyword argument 'smooth_software'

### ISSUE THREAD

**Issue by alpinho** [neurospin/pypreprocess#88]
TypeError                                 Traceback (most recent call last)
/home/analu/git_repo/pypreprocess/examples/nipype_preproc_spm_nyu.py in <module>()
     33 # preprocess the data
     34 results = do_subjects_preproc(jobfile, dataset_dir=os.path.join(
---> 35     dataset_dir, "nyu_rest"))

/home/analu/git_repo/pypreprocess/pypreprocess/nipype_preproc_spm_utils.pyc in do_subjects_preproc(subject_factory, **preproc_params)
   1752     # run classic preproc
   1753     preproc_subject_data = Parallel(n_jobs=n_jobs)(delayed(do_subject_preproc)(
-> 1754             subject_data, **preproc_params) for subject_data in subjects)
   1755 
   1756     # run DARTEL

/usr/lib/python2.7/dist-packages/joblib/parallel.pyc in __call__(self, iterable)
    651             self._iterating = True
    652             for function, args, kwargs in iterable:
--> 653                 self.dispatch(function, args, kwargs)
    654 
    655             if pre_dispatch == "all" or n_jobs == 1:

/usr/lib/python2.7/dist-packages/joblib/parallel.pyc in dispatch(self, func, args, kwargs)
    398         """
    399         if self._pool is None:
--> 400             job = ImmediateApply(func, args, kwargs)
    401             index = len(self._jobs)
    402             if not _verbosity_filter(index, self.verbose):

/usr/lib/python2.7/dist-packages/joblib/parallel.pyc in __init__(self, func, args, kwargs)
    136         # Don't delay the application, to avoid keeping the input
    137         # arguments in memory
--> 138         self.results = func(*args, **kwargs)
    139 
    140     def get(self):

/home/analu/git_repo/pypreprocess/pypreprocess/nipype_preproc_spm_utils.pyc in do_subject_preproc(subject_data, deleteorient, slice_timing, slice_order, interleaved, refslice, TR, TA, slice_timing_software, realign, realign_reslice, register_to_mean, realign_software, coregister, coregister_reslice, coreg_anat_to_func, coregister_software, segment, normalize, dartel, fwhm, anat_fwhm, func_write_voxel_sizes, anat_write_voxel_sizes, smooth_software, hardlink_output, report, cv_tc, parent_results_gallery, last_stage, preproc_undergone, prepreproc_undergone, caching, **kwargs)
   1383             report=report,
   1384             hardlink_output=hardlink_output,
-> 1385             smooth_software=smooth_software
   1386             )
   1387 

TypeError: _do_subject_normalize() got an unexpected keyword argument 'smooth_software'

**Comment by dohmatob** [comment]
Should be fixed.
