### ISSUE TITLE
Tsdiffana -- just adding images

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#90]
![ts1](https://cloud.githubusercontent.com/assets/234454/6938784/7c4f0dd4-d866-11e4-98d9-a8085d21ea34.png)
![ts2](https://cloud.githubusercontent.com/assets/234454/6938794/8714edc4-d866-11e4-85b5-cfbb1210b185.png)

**Comment by dohmatob** [comment]
This looks really awesome!

Som suggestions though:
* change label "scaled variance" to "coefficient of variation"
* Condence all the QA to 2 or three most informative thumbnails
(concatenate results for different sessions / runs, etc.)



2015-04-01 11:59 GMT+02:00 bthirion <notifications@github.com>:

> [image: ts1]
> <https://cloud.githubusercontent.com/assets/234454/6938784/7c4f0dd4-d866-11e4-98d9-a8085d21ea34.png>
> [image: ts2]
> <https://cloud.githubusercontent.com/assets/234454/6938794/8714edc4-d866-11e4-85b5-cfbb1210b185.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/90>.
>



-- 
DED

**Comment by bthirion** [comment]
two slightly more messy examples (putting images into the wiki) 
![ts3](https://cloud.githubusercontent.com/assets/234454/6941431/420f3256-d880-11e4-99d6-522ba8d8f9c0.png)
![ts4](https://cloud.githubusercontent.com/assets/234454/6941418/1c7f3374-d880-11e4-818d-06bb151b826d.png)

**Comment by dohmatob** [comment]
Nice. It be good to send a PR (I don't see any) already, so we can start
reviewing the feature and the code.

On Wed, Apr 1, 2015 at 3:07 PM, bthirion <notifications@github.com> wrote:

> two slightly more messy examples (putting images into the wiki)
> [image: ts3]
> <https://cloud.githubusercontent.com/assets/234454/6941431/420f3256-d880-11e4-99d6-522ba8d8f9c0.png>
> [image: ts4]
> <https://cloud.githubusercontent.com/assets/234454/6941418/1c7f3374-d880-11e4-818d-06bb151b826d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/90#issuecomment-88473594>
> .
>



-- 
DED

**Comment by dohmatob** [comment]
Please could you polish the labels (axes, legends, etc.) and concatenate results for different sessions (and separate with a broken vertical line)

**Comment by dohmatob** [comment]
Also, It'd be nice to have more comprehensive label / legends. For example, what is "variation" ? etc.

**Comment by dohmatob** [comment]
Any progress on the legends, etc. ?

**Comment by lesteve** [comment]
This should probably be closed in favour of #100.
